// constants/design-system.ts — MASTRO OS Design System Premium

export const DS = {
  colors: {
    teal:         '#0A8A7A',
    tealLight:    '#E6F4F2',
    tealDark:     '#076D62',
    dark:         '#0B1F2A',
    darkMid:      '#122535',
    darkLight:    '#1a3040',
    background:   '#F4F6F8',
    surface:      '#FFFFFF',
    surfaceAlt:   '#F9FAFB',
    border:       '#E8EAED',
    borderLight:  '#F0F2F4',
    borderDark:   '#D1D5DB',
    textPrimary:  '#0D1117',
    textSecondary:'#374151',
    textMuted:    '#6B7280',
    textFaint:    '#9CA3AF',
    red:          '#DC4444',
    redLight:     '#FEF2F2',
    green:        '#0F7B5A',
    greenLight:   '#ECFDF5',
    amber:        '#D97706',
    amberLight:   '#FFFBEB',
    blue:         '#2563EB',
    blueLight:    '#EFF6FF',
    purple:       '#7C3AED',
    purpleLight:  '#F5F3FF',
    fabio:        '#0A8A7A',
    lidia:        '#BE185D',
    lidiaLight:   '#FDF0F6',
  },
  fonts: {
    ui:      '"Plus Jakarta Sans", "DM Sans", system-ui, -apple-system, sans-serif',
    mono:    '"JetBrains Mono", "DM Mono", monospace',
    display: '"Plus Jakarta Sans", system-ui, sans-serif',
  },
  radius: { xs:4, sm:6, md:10, lg:14, xl:18, '2xl':24, full:9999 },
  shadow: {
    xs:  '0 1px 3px rgba(0,0,0,0.06)',
    sm:  '0 2px 8px rgba(0,0,0,0.08)',
    md:  '0 4px 16px rgba(0,0,0,0.1)',
    lg:  '0 8px 32px rgba(0,0,0,0.12)',
    xl:  '0 16px 48px rgba(0,0,0,0.16)',
    dark:'0 8px 32px rgba(0,0,0,0.4)',
  },
}

export const STATE_COLORS: Record<string, { bg: string; color: string }> = {
  attivo:       { bg: '#ECFDF5', color: '#0F7B5A' },
  in_sviluppo:  { bg: '#EFF6FF', color: '#2563EB' },
  pausa:        { bg: '#FFFBEB', color: '#D97706' },
  completato:   { bg: '#E6F4F2', color: '#0A8A7A' },
  aperto:       { bg: '#F0F2F4', color: '#6B7280' },
  in_corso:     { bg: '#EFF6FF', color: '#2563EB' },
  urgente:      { bg: '#FEF2F2', color: '#DC4444' },
  lead:         { bg: '#F5F3FF', color: '#7C3AED' },
  proposta:     { bg: '#FFFBEB', color: '#D97706' },
  chiuso_vinto: { bg: '#ECFDF5', color: '#0F7B5A' },
  chiuso_perso: { bg: '#FEF2F2', color: '#DC4444' },
}

export const LOG_TYPE_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  nota:       { label: 'Nota',       color: '#6B7280', bg: '#F0F2F4' },
  aggiornamento: { label: 'Update',  color: '#2563EB', bg: '#EFF6FF' },
  problema:   { label: 'Problema',   color: '#DC4444', bg: '#FEF2F2' },
  milestone:  { label: 'Milestone',  color: '#0F7B5A', bg: '#ECFDF5' },
  decisione:  { label: 'Decisione',  color: '#D97706', bg: '#FFFBEB' },
  call:       { label: 'Call',       color: '#7C3AED', bg: '#F5F3FF' },
}
